# Generated by Django 4.1.7 on 2023-04-03 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseMetadata',
            fields=[
                ('metadataId', models.AutoField(primary_key=True, serialize=False)),
                ('testName', models.CharField(max_length=255)),
                ('featureGroup', models.CharField(blank=True, max_length=255, null=True)),
                ('testGroup', models.CharField(max_length=255)),
                ('testPath', models.CharField(max_length=512)),
                ('testVersion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'TestCaseMetadata',
            },
        ),
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('testId', models.AutoField(primary_key=True, serialize=False)),
                ('firstExecution', models.DateTimeField(blank=True, null=True)),
                ('lastExecution', models.DateTimeField(blank=True, null=True)),
                ('executed', models.BooleanField(default=False)),
                ('metaDataId', models.ForeignKey(db_column='metaDataId', on_delete=django.db.models.deletion.CASCADE, to='jftf_core_api.testcasemetadata')),
            ],
            options={
                'db_table': 'TestCases',
            },
        ),
        migrations.CreateModel(
            name='TestReportInformation',
            fields=[
                ('testReportInformationId', models.AutoField(primary_key=True, serialize=False)),
                ('startupTimestamp', models.DateTimeField()),
                ('endTimestamp', models.DateTimeField()),
                ('testDuration', models.TimeField()),
                ('errorMessages', models.TextField(blank=True, null=True)),
                ('loggerOutput', models.TextField(blank=True, null=True)),
                ('executionResult', models.CharField(max_length=255)),
                ('testId', models.ForeignKey(db_column='testId', on_delete=django.db.models.deletion.CASCADE, to='jftf_core_api.testcases')),
            ],
            options={
                'db_table': 'TestReportInformation',
            },
        ),
        migrations.CreateModel(
            name='TestReports',
            fields=[
                ('reportId', models.AutoField(primary_key=True, serialize=False)),
                ('testId', models.ForeignKey(db_column='testId', on_delete=django.db.models.deletion.CASCADE, to='jftf_core_api.testcases')),
                ('testReportInformationId', models.ForeignKey(db_column='testReportInformationId', on_delete=django.db.models.deletion.CASCADE, to='jftf_core_api.testreportinformation')),
            ],
            options={
                'db_table': 'TestReports',
            },
        ),
    ]
