# Generated by Django 4.2 on 2023-05-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jftf_core_api', '0002_apply_boolean_default_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreportinformation',
            name='endTimestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testreportinformation',
            name='startupTimestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
