# Generated by Django 4.2 on 2023-05-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jftf_core_api', '0003_alter_testreportinformation_endtimestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreportinformation',
            name='endTimestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='testreportinformation',
            name='startupTimestamp',
            field=models.DateTimeField(),
        ),
    ]
